# Generated by Django 3.2.4 on 2021-06-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_password_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
